### ISSUE TITLE
Change modifier key?

### ISSUE THREAD

**Issue by jchatard** [mortalis13/Bookmark-Shortcuts#1]
Hi,

Thanks for this good extension, that's a great idea! :+1: 

Would it be possible to change the modifier key and map it to any other key?

I'm under linux and change the font size of my web pages on regular basis. I'm French and my keyboard as the `6` and `-` dash on the same key. So when I want to decrease text size (which is `CTRL` + `-`), I'm going to my 6th bookmark.

I'd like to map `CTRL` to Windows (`SUPER`) key with your extension.

Thank you,
Jérémy

**Comment by mortalis13** [comment]
Hi.
The current addons engine doesn't allow to change shortcuts in the options, it's hardcoded.
But it's easy to change them in the code.

The problem is that there is a limited set of key modifiers compared to the old system.
Check this: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands.
The **Shortcut values** section tells about possible combinations.

So for Linux it could be **Alt+N, Ctrl+N, Alt+Shift+N, Ctrl+Shift+N**.
The **Alt+N** is occupied by the browser.

So I created 2 addon versions for **+Shift** keys.
Check the [Versions](https://addons.mozilla.org/en-US/firefox/addon/bookmark-shortcuts/versions/) page and '**...lcs, ...las**' installs. They are for '*Linux Ctrl Shift, Linux Alt Shift*'.
Shortcuts for new tab bookmarks are **Alt+Shift** and **Ctrl+Shift** respectively.

If you confused just unzip the **.xpi** file (which you can download from the install button context menu) with any archiver (like 7Zip) and check the **manifest.json** file with a text editor. It's a text file with the corresponding shortcuts.

---

You could also experiment with the code yourself. Unzip the addon file like I desribed, change the shortcuts in the manifest.
Also chenge its **name** in the manifest so it be unique among other addons (like "BS_Test").
Then zip it again. It's the modified addon now. Though it needs to be digitally signed so you can install it in Firefox.
It's easy to achieve, just register on the [addons.mozilla.org](https://addons.mozilla.org) and submit that zip file.
It will be from the menu **Tools -> Submit a New Addon**, then select **On your own** option and upload that file. Then you can download the signed version of the addon and just drag it to you browser to install. This way you can customize it for your needs.

![https://i.imgur.com/5qlGVQX.png](https://i.imgur.com/5qlGVQX.png)

If you need any help on this procedure I'll be glad to help.

---

Also, as an advice, you could use your **Ctrl+Num-** shortcut (if you have numpad) to reduce your font size.

**Comment by jchatard** [comment]
Thanks for your reply! :+1: 

I'll check this out pretty soon.

Cheers,
Jérémy
